/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/fennec_-_rocket_league_car_1k_Texture.glb 
Author: Jako (https://sketchfab.com/fairlight51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fennec-rocket-league-car-5b43b1b6eeb4a12a29671df3418f57a
Title: Fennec - Rocket League Car
*/

import { useLayoutEffect, useRef, useState } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import type { Group } from "three";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

// const BOUNDS = {
//   minX: -400,
//   maxX: 400,
//   minZ: -400,
//   maxZ: 400,
// };

function useKeyboard() {
  const keys = useRef<{ [key: string]: boolean }>({});

  useLayoutEffect(() => {
    const down = (e: KeyboardEvent) => (keys.current[e.code] = true);
    const up = (e: KeyboardEvent) => (keys.current[e.code] = false);

    window.addEventListener("keydown", down);
    window.addEventListener("keyup", up);

    return () => {
      window.removeEventListener("keydown", down);
      window.removeEventListener("keyup", up);
    };
  }, []);

  return keys;
}

export const FLOOR_HEIGHT = 9.3;
export const NB_FLOORS = 7;

export function Fennec(props: any) {
  const [timelineComplete, setTimelineComplete] = useState<boolean>(false);
  const frontWheels = useRef<Group | null>(null);
  const frontRightTire = useRef<Group | null>(null);
  const frontLeftTire = useRef<Group | null>(null);
  const bodyChassis = useRef<Group | null>(null);
  const bodyFinishing = useRef<Group | null>(null);
  const bodyMainBase = useRef<Group | null>(null);
  const bodyHeadlights = useRef<Group | null>(null);
  const mainBody = useRef<Group | null>(null);
  const backWheels = useRef<Group | null>(null);
  const backLeftTire = useRef<Group | null>(null);
  const backRightTire = useRef<Group | null>(null);
  const body = useRef<Group | null>(null);

  const keys = useKeyboard();

  const joystick = props.joystick;

  const { nodes, materials } = useGLTF(
    "./models/fennec_-_rocket_league_car_1k_Texture.glb",
  ) as any;
  const ref = useRef<Group | null>(null);
  const t1 = useRef<any>(null);

  const scroll = useScroll();
  // useFrame(() => {
  //   t1.current.seek(scroll.offset * t1.current.duration());
  // });
  useFrame(({ camera }, delta) => {
    // keep your GSAP scroll animation
    // if (t1.current && scroll) {
    //   t1.current.seek(scroll.offset * t1.current.duration());
    // }
    if (!t1.current && !scroll) return;
    t1.current.seek(scroll.offset * t1.current.duration());
    const progress = scroll.offset;

    if (progress >= 0.99 && !timelineComplete) {
      setTimelineComplete(true);
    }

    if (!ref.current || !timelineComplete) return;

    const moveSpeed = 50;
    const turnSpeed = 2;
    // Turn

    const keyboardSteer =
      (keys.current["KeyD"] ? 1 : 0) - (keys.current["KeyA"] ? 1 : 0);

    // joystick.x is -1..1
    const steer = THREE.MathUtils.clamp(
      keyboardSteer + joystick.current.x,
      -1,
      1,
    );
    if (Math.abs(steer) > 0.05) {
      ref.current.rotation.y -= steer * turnSpeed * delta;

      frontLeftTire.current!.rotation.z = -steer * 0.4;
      frontRightTire.current!.rotation.z = -steer * 0.4;
    } else {
      frontLeftTire.current!.rotation.z = 0;
      frontRightTire.current!.rotation.z = 0;
    }
    const keyboardThrottle =
      (keys.current["KeyW"] ? 1 : 0) - (keys.current["KeyS"] ? 1 : 0);

    // joystick.y:
    // up = -1
    // down = +1
    const throttle = THREE.MathUtils.clamp(
      keyboardThrottle - joystick.current.y,
      -1,
      1,
    );

    // if (
    //   (keys.current["KeyA"] && keys.current["KeyW"]) ||
    //   (keys.current["KeyD"] && keys.current["KeyS"])
    // ) {
    //   ref.current.rotation.y += turnSpeed * delta;
    // }
    // else if (keys.current["KeyA"]) {
    //   frontLeftTire.current!.rotation.z = 0.2;
    //   frontRightTire.current!.rotation.z = 0.2;
    // }
    // else if (
    //   (keys.current["KeyD"] && keys.current["KeyW"]) ||
    //   (keys.current["KeyA"] && keys.current["KeyS"])
    // ) {
    //   ref.current.rotation.y -= turnSpeed * delta;
    // }
    // else if (keys.current["KeyD"]) {
    //   frontLeftTire.current!.rotation.z = -0.2;
    //   frontRightTire.current!.rotation.z = -0.2;
    // }
    // else {
    //   frontLeftTire.current!.rotation.z = 0;
    //   frontRightTire.current!.rotation.z = 0;
    // }

    // Forward direction
    const forward = new THREE.Vector3(10, 0, 0);
    forward.applyQuaternion(ref.current.quaternion);

    if (Math.abs(throttle) > 0.05) {
      ref.current.position.addScaledVector(
        forward,
        throttle * moveSpeed * delta,
      );

      const wheelSpeed = throttle * 8 * delta;

      // frontLeftTire.current!.rotation.y += wheelSpeed;
      // frontRightTire.current!.rotation.y += wheelSpeed;
      backLeftTire.current!.rotation.y += wheelSpeed;
      backRightTire.current!.rotation.y += wheelSpeed;
    }

    // Move forward / backward
    // if (keys.current["KeyW"]) {
    //   ref.current.position.addScaledVector(forward, moveSpeed * delta);
    //   frontLeftTire.current!.rotation.y += 8 * delta;
    //   frontRightTire.current!.rotation.y += 8 * delta;
    //   backLeftTire.current!.rotation.y += 8 * delta;
    //   backRightTire.current!.rotation.y += 8 * delta;
    // }
    // if (keys.current["KeyS"]) {
    //   ref.current.position.addScaledVector(forward, -moveSpeed * delta);
    //   frontLeftTire.current!.rotation.y -= 8 * delta;
    //   frontRightTire.current!.rotation.y -= 8 * delta;
    //   backLeftTire.current!.rotation.y -= 8 * delta;
    //   backRightTire.current!.rotation.y -= 8 * delta;
    // }
    if (ref.current.position.length() > 5000) {
      ref.current.position.set(0, 0, 0);
    }

    // Camera offset (behind & above the car)
    const offset = new THREE.Vector3(-200, 120, 0);

    // Rotate offset with car direction
    offset.applyQuaternion(ref.current.quaternion);

    const targetPos = ref.current.position.clone().add(offset);

    // Smooth follow
    camera.position.lerp(targetPos, 0.08);
    camera.lookAt(ref.current.position);
  });

  useLayoutEffect(() => {
    t1.current = gsap.timeline({
      paused: true,
      onComplete: () => {
        // console.log("Timeline has ended!");
        setTimelineComplete(true);
        // You can set a state here or trigger any action
      },
    });
    // frontWheels.current?.position.setZ(100);
    // body.current?.position.setY(100);
    // bodyChassis.current?.position.setZ(1.2);
    bodyFinishing.current?.position.setZ(2.2);
    bodyMainBase.current?.position.setZ(1);
    bodyHeadlights.current?.position.setZ(0.5);
    mainBody.current?.position.setZ(2.2);
    // ref.current?.rotateY(-Math.PI * 2);
    if (ref.current) {
      const arrow = new THREE.ArrowHelper(
        new THREE.Vector3(10, 0, 0),
        ref.current.position,
        100,
        0xff0000,
      );
      ref.current.add(arrow);
      t1.current.to(bodyMainBase.current?.position, {
        duration: 1,
        z: "-=1",
      });
      t1.current.to(bodyHeadlights.current?.position, {
        duration: 0.2,
        z: "-=1",
      });
      t1.current.to(bodyFinishing.current?.position, {
        duration: 1.5,
        z: "-=2.2",
      });
      t1.current.to(mainBody.current?.position, {
        duration: 1.5,
        z: "-=2.2",
        delay: -0.5,
      });
      t1.current.to(
        ref.current.rotation,
        {
          duration: 5,
          yoyo: true,
          y: "+=" + Math.PI * 2.5,
        },
        0.5,
      );
    }
  }, []);

  return (
    <group {...props} dispose={null} ref={ref}>
      <group ref={frontWheels}>
        // front right tire
        <group
          ref={frontRightTire}
          position={[45.393, 10.971, -29.963]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-76.424, 76.424, 76.424]}
        >
          <mesh
            geometry={nodes["Alpha_-_FR_(Fennec)_Alpha_Rim_0"].geometry}
            material={materials.Alpha_Rim}
          />
          <mesh
            geometry={nodes["Alpha_-_FR_(Fennec)_Dieci_Tread_0"].geometry}
            material={materials.Dieci_Tread}
          />
        </group>
        //front left tire
        <group
          ref={frontLeftTire}
          position={[45.585, 10.971, 29.092]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={76.424}
        >
          <mesh
            geometry={nodes["Alpha_-_FL_(Fennec)_Alpha_Rim_0"].geometry}
            material={materials.Alpha_Rim}
          />
          <mesh
            geometry={nodes["Alpha_-_FL_(Fennec)_Dieci_Tread_0"].geometry}
            material={materials.Dieci_Tread}
          />
        </group>
      </group>
      <group ref={backWheels}>
        // back left tire
        <group
          position={[-39.833, 12.069, -30.363]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-82.349, 82.349, 82.349]}
          ref={backLeftTire}
        >
          <mesh
            geometry={nodes["Alpha_-_BR_(Fennec)_Alpha_Rim_0"].geometry}
            material={materials.Alpha_Rim}
          />
          <mesh
            geometry={nodes["Alpha_-_BR_(Fennec)_Dieci_Tread_0"].geometry}
            material={materials.Dieci_Tread}
          />
        </group>
        // back right tire
        <group
          position={[-39.917, 12.069, 30.259]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={82.349}
          ref={backRightTire}
        >
          <mesh
            geometry={nodes["Alpha_-_BL_(Fennec)_Alpha_Rim_0"].geometry}
            material={materials.Alpha_Rim}
          />
          <mesh
            geometry={nodes["Alpha_-_BL_(Fennec)_Dieci_Tread_0"].geometry}
            material={materials.Dieci_Tread}
          />
        </group>
      </group>
      // Main body
      <group ref={body}>
        <group
          position={[-3.516, 16.743, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <group ref={bodyChassis}>
            <group ref={bodyMainBase}>
              <mesh
                geometry={nodes.Fennec_Fennec_Chassis_0.geometry}
                material={materials.Fennec_Chassis}
              />
            </group>
            <group ref={bodyHeadlights}>
              <mesh
                geometry={nodes.Fennec_Headlights_0.geometry}
                material={materials.Headlights}
              />
            </group>
            <group ref={mainBody}>
              <mesh
                geometry={nodes["Fennec_Fennec_-_Body_0"].geometry}
                material={materials["Fennec_-_Body"]}
              />
            </group>
          </group>
          <group ref={bodyFinishing}>
            <mesh
              geometry={nodes.Fennec_Window_0.geometry}
              material={materials.Window}
            />
            <mesh
              geometry={nodes.Fennec_Paint_0.geometry}
              material={materials.Paint}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/fennec_-_rocket_league_car_1k_Texture.glb");
